/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPokemonListRouteImport } from './routes/api/pokemon-list'
import { Route as ApiMatchRouteImport } from './routes/api/match'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPokemonListRoute = ApiPokemonListRouteImport.update({
  id: '/api/pokemon-list',
  path: '/api/pokemon-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchRoute = ApiMatchRouteImport.update({
  id: '/api/match',
  path: '/api/match',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/match': typeof ApiMatchRoute
  '/api/pokemon-list': typeof ApiPokemonListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/match': typeof ApiMatchRoute
  '/api/pokemon-list': typeof ApiPokemonListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/match': typeof ApiMatchRoute
  '/api/pokemon-list': typeof ApiPokemonListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/match' | '/api/pokemon-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/match' | '/api/pokemon-list'
  id: '__root__' | '/' | '/api/match' | '/api/pokemon-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMatchRoute: typeof ApiMatchRoute
  ApiPokemonListRoute: typeof ApiPokemonListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pokemon-list': {
      id: '/api/pokemon-list'
      path: '/api/pokemon-list'
      fullPath: '/api/pokemon-list'
      preLoaderRoute: typeof ApiPokemonListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match': {
      id: '/api/match'
      path: '/api/match'
      fullPath: '/api/match'
      preLoaderRoute: typeof ApiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMatchRoute: ApiMatchRoute,
  ApiPokemonListRoute: ApiPokemonListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
